SpeedTypingASP/Areas/Admin/Controllers/TextEditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SpeedTypingASP.Domain;
using SpeedTypingASP.Domain.Entities;
using SpeedTypingASP.Service;

namespace SpeedTypingASP.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextEditController : Controller
    {
        private readonly DataManager dataManager;

        public TextEditController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Edit(string textName)
        {
            var entity = dataManager.Texts.GetTextByName(textName);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(Text model)
        {
            //todo вынести вместе с ADD
            if (ModelState.IsValid)
            {
                try
                {
                    dataManager.Texts.SaveText(model);
                    return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
                }
                catch (ArgumentException e)
                {
                    ModelState.AddModelError("", e.Message);
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", "Ошибка! Проверьте корректность введенных данных");
                }
            }
            return View(model);
        }
        public IActionResult Add()
        {
            return View(new Text(){Id = Guid.NewGuid().ToString()});
        }
        [HttpPost]
        public IActionResult Add(Text model)
        {
            if (ModelState.IsValid)
            {
                model.Id = default;
                try
                {
                    dataManager.Texts.SaveText(model);
                    return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
                }
                catch (ArgumentException e)
                {
                    ModelState.AddModelError("", e.Message);
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", "Ошибка! Проверьте корректность введенных данных");
                }
            }
            return View(model);
        }
        public IActionResult Delete(string textName)
        {
            dataManager.Texts.DeleteTextByName(textName);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

SpeedTypingASP/Areas/Admin/Views/TextEdit/Add.cshtml
@model Text
@{
    var strTitle = "Добавление текста";
    ViewBag.Title = strTitle;
}

<div class="text-edit">
    <div class="container">
        <div class="text-edit__body">
            <div class="text-edit__wrapper">
                <form asp-area="Admin"
                      asp-controller="TextEdit"
                      asp-action="Add"
                      method="post"
                      enctype="multipart/form-data">
                    <input type="hidden" asp-for="Id" />
                    <h2 class="text-edit__heading">
                        @strTitle
                    </h2>
                    <div class="error-message" asp-validation-summary="All"></div>
                    <input asp-for="Title" value="@Model.Title" placeholder="Название текста"
                           class="text-edit__edit-title-input">
                    <div class="text-edit__text-wrapper">
                        <textarea asp-for="TextContent" placeholder="Содержание" class="text-edit__textarea" id="text-edit__textarea">
                        </textarea>
                    </div>
                    <div class="text-edit__text-wrapper">
                        <div class="text-edit__character-edit-wrapper" id="text-edit__character-edit-wrapper">

                        </div>
                        <div class="text-edit__character-edit-buttons">
                            <div class="text-selection__button admin-panel__text-edit-button" id="add-text-to-change-btn">
                                Добавить текст для изменения
                            </div>
                            <div class="text-selection__button admin-panel__text-edit-button" id="change-text-btn">
                                Изменить
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="admin-panel__button text-edit__save-changes-button">
                        Сохранить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="~/JS/text-edit.js"></script>
<script src="~/JS/replace-characters.js"></script>

SpeedTypingASP/Areas/Admin/Views/TextEdit/Edit.cshtml
@model Text
@{
    var strTitle = "Редактирование текста";
    ViewBag.Title = strTitle;
}

<div class="text-edit">
    <div class="container">
        <div class="text-edit__body">
            <div class="text-edit__wrapper">
                <form asp-area="Admin"
                      asp-controller="TextEdit"
                      asp-action="Edit"
                      method="post"
                      enctype="multipart/form-data">
                    <input type="hidden" asp-for="Id" />
                    <h2 class="text-edit__heading">
                        @strTitle
                    </h2>
                    <div class="error-message" asp-validation-summary="All"></div>
                    <input asp-for="Title" value="@Model.Title"
                           class="text-edit__edit-title-input">
                    <div class="text-edit__text-wrapper">
                        <textarea asp-for="TextContent" placeholder="Содержание" class="text-edit__textarea" id="text-edit__textarea">
                        @Model.TextContent
                    </textarea>
                    </div>
                    <div placeholder="Text" class="text-edit__text-wrapper">
                        <div class="text-edit__character-edit-wrapper" id="text-edit__character-edit-wrapper">

                        </div>
                        <div class="text-edit__character-edit-buttons">
                            <div class="text-selection__button admin-panel__text-edit-button" id="add-text-to-change-btn">
                                Добавить текст для изменения
                            </div>
                            <div class="text-selection__button admin-panel__text-edit-button" id="change-text-btn">
                                Изменить
                            </div>
                        </div>
                    </div>  
                    <button type="submit" class="admin-panel__button text-edit__save-changes-button">
                        Сохранить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="~/JS/text-edit.js"></script>
<script src="~/JS/replace-characters.js"></script>